### ISSUE TITLE
OSCAL 2019: Poster Messages

### ISSUE THREAD

**Issue by kleidieski** [OpenLabsHackerspace/OSCAL-branding#3]
### **Suggested Message for main poster**

1. Open source might affect the way the system works. Proceed?
Next >    Cancel

### Proprietary/Open Source software

2. The trial period has expired
Buy license    Go open source

3. This software is not available in your country.
Use cracked version    Use open source alternative

4. Proprietary software might be harmful to your computer.
OK    Cancel

5. This wizard will help you detect illegal content on your computer.
Next    Cancel

6. Not enough storage is available to store your pictures.
Buy more storage    Delete useless pictures    Host your own files

7. This wizard will install proprietary software on your computer.
Next    Cancel

8. Do you want to allow corporations to make changes to this computer?
Yes    No

9. You’ve been using this version for too long. If you don't upgrade, your computer will stop working.
Upgrade    Hack

10. Do you want to stop the ads and enjoy unlimited service?
Buy premium service    Go Open Source

11. You will not be able to downgrade after installation
Install now    Cancel

12. We updated our Privacy Policy. If you don’t wish to agree, you’ll need to discontinue using proprietary software.
Agree    Do not Agree

### Proprietary/Open Hardware

13. The planet is running low on resources.
Fix hardware    Buy new hardware

14. Battery condition is poor.
Replace Battery    Replace Phone

15. Battery not charging. This cable is not certified.
Buy certified cable    Get open hardware

16. The system detected open source hardware and cannot continue.
Change the hardware    Change the system

17. By continuing, you agree that we can kill your device at any time.
Continue    Go back

18. Trust corporations? Your settings and data will be accessible by them when connected on the internet.
Trust    Don’t trust

19. This wizard will connect to the internet and help us determine if your hardware is old enough to die.
Exit    Next

20. Warning! Spy chip detected on your hardware.
Ok    Not OK

21. This hardware will stop working if you don’t renew your subscription.
Renew subscription    Change hardware

### Online Privacy

22. We use cookies to track your children.
Okay    Deny

23. We updated our privacy policy. You are now exposed.
Accept    Learn more    Deny

24. Share your 200 GB of intimate content with your family members over the cloud.
Share plan    Not Now

25. You may delete this file, but we wont.
Delete for myself    Delete for everyone    Learn more…

26. Your computer ran into a problem and needs to restart. We’re just collecting any information we can.
Okay    Unplug

27. Choose destination location.
Your disk    The cloud

28. This page will redirect you to many other pages.
Continue    Go back

29. Can’t find a camera. Make sure the camera is turned on and pointing at you all the time.
Ok    Cover the camera

30. We prepared a list of products you might like, based on your intimate messages.
Show list    Close account

31. The government wants to access your personal data
OK    Ignore    Learn more…

32. We care about your memories. How about you?
Share    Delete

33. Your connection is not private! Corporations or governments might be trying to steal your personal information.
Ignore    Back to safety

### Online freedom & Political

34. The system is failing and is going to collapse
Restart    Ignore

35. We found corrupt members in the system
Report    Uninstall    Ignore

36. Your keyboard has been disabled because of what you were typing.
OK    Reactivate

37. Found infected thoughts in this document. Remove them?
Yes    No

38. Your account has been blocked. It is required that you should not discuss politics on the internet.
Complain    Use encryption

39. Internet freedom is not available in your country or region. 
Sorry about that.
Hack    Ignore

40. It is recommended that you close your mouth before continuing.
OK    Not OK

41. Society is low on memory!
Abort    Restore Memory

42. Your post is too long. Try explaining your thoughts in emojis.
OK    Hack

43. There is a problem with this website’s political agenda.
Proceed anyway    Back to safety

### Dystopian technology & Futurism

44. A crash occured to your self-driving car. We’ll try to save your family. 
Submit report    Cancel

45. Would you like to submit a review for your ex?
Review    I’ll review later    Cancel

46. Type the name of a neighbour, family member or friend, and the we will trace them for you.
OK    Cancel    Browse

47. See the full list of people who stalked you in the last 90 days.
Try free for 1 Month    Delete profile

### Open Knowledge

48. Select license before sharing.
Copyright    Creative commons    Public domain

49. You do not have enough privileges to access public interest data.
Ok    Not OK

50. You currently don’t have permission to access public-funded knowledge.
OK    Request Permission

**Comment by kleidieski** [comment]
Suggested main message: *this might affect the way the system works. Proceed?*

**Comment by rskikuli** [comment]
Please proceed with this as main message @kleidieski 
> this will affect the way the system works. Proceed?

I made a small change, because we wantto show that we are determined :)
Working with the other messages.

**Comment by rskikuli** [comment]
Hey @kleidieski here is the feedback for the messages. All the ones that will be ticked ones are considered 'approved'.


**Proprietary/Open Source software**

- [ ] The trial period has expired
Buy license Go open source
- [ ] This software is not available in your country.
Use cracked version Use open source alternative
- [ ] Proprietary software might be harmful to your computer.
    OK Cancel
- [ ] This wizard will help you detect illegal content on your computer.
    Next Cancel
- [ ] Not enough storage is available to store your pictures.
    Buy more storage Delete useless pictures Host your own files
- [ ] This wizard will install proprietary software on your computer.
    Next Cancel
- [ ] Do you want to allow corporations to make changes to this computer?
    Yes No
- [ ] You’ve been using this version for too long. If you don't upgrade, your computer will stop working.
    Upgrade Hack
- [ ] Do you want to stop the ads and enjoy unlimited service?
    Buy premium service Go Open Source
- [ ] You will not be able to downgrade after installation
    Install now Cancel
- [ ] We updated our Privacy Policy. If you don’t wish to agree, you’ll need to discontinue using proprietary software.
    Agree Do not Agree

**Proprietary/Open Hardware**
- [ ] The planet is running low on resources.
    Fix hardware Buy new hardware
- [ ] Battery condition is poor.
    Replace Battery Replace Phone
- [ ] Battery not charging. This cable is not certified.
    Buy certified cable Get open hardware
- [ ] The system detected open source hardware and cannot continue.
    Change the hardware Change the system
- [ ] By continuing, you agree that we can kill your device at any time.
    Continue Go back
- [ ] Trust corporations? Your settings and data will be accessible by them when connected on the internet.
    Trust Don’t trust
- [ ] This wizard will connect to the internet and help us determine if your hardware is old enough to die.
    Exit Next
- [ ] Warning! Spy chip detected on your hardware.
    Ok Not OK
- [ ] This hardware will stop working if you don’t renew your subscription.
    Renew subscription Change hardware

**Online Privacy**
- [ ] We use cookies to track your children.
    Okay Deny
- [ ] We updated our privacy policy. You are now exposed.
    Accept Learn more Deny
- [ ] Share your 200 GB of intimate content with your family members over the cloud.
    Share plan Not Now
- [ ] You may delete this file, but we wont.
    Delete for myself Delete for everyone Learn more…
- [ ] Your computer ran into a problem and needs to restart. We’re just collecting any information we can.
    Okay Unplug
- [ ] Choose destination location.
    Your disk The cloud
- [ ] This page will redirect you to many other pages.
    Continue Go back
- [ ] Can’t find a camera. Make sure the camera is turned on and pointing at you all the time.
    Ok Cover the camera
- [ ] We prepared a list of products you might like, based on your intimate messages.
    Show list Close account
- [ ] The government wants to access your personal data
    OK Ignore Learn more…
- [ ] We care about your memories. How about you?
    Share Delete
- [ ] Your connection is not private! Corporations or governments might be trying to steal your personal information.
    Ignore Back to safety

**Online freedom & Political**
- [ ] The system is failing and is going to collapse
    Restart Ignore
- [ ] We found corrupt members in the system
    Report Uninstall Ignore
- [ ] Your keyboard has been disabled because of what you were typing.
    OK Reactivate
- [ ] Found infected thoughts in this document. Remove them?
    Yes No
- [ ] Your account has been blocked. It is required that you should not discuss politics on the internet.
    Complain Use encryption
- [ ] Internet freedom is not available in your country or region.
    Sorry about that.
    Hack Ignore
- [ ] It is recommended that you close your mouth before continuing.
    OK Not OK
- [ ] Society is low on memory!
    Abort Restore Memory
- [ ] Your post is too long. Try explaining your thoughts in emojis.
    OK Hack
- [ ] There is a problem with this website’s political agenda.
    Proceed anyway Back to safety

**Dystopian technology & Futurism**
- [ ] A crash occured to your self-driving car. We’ll try to save your family.
    Submit report Cancel
- [ ] Would you like to submit a review for your ex?
    Review I’ll review later Cancel
- [ ] Type the name of a neighbour, family member or friend, and the we will trace them for you.
    OK Cancel Browse
- [ ] See the full list of people who stalked you in the last 90 days.
    Try free for 1 Month Delete profile

**Open Knowledge**
- [ ] Select license before sharing.
    Copyright Creative commons Public domain
- [ ] You do not have enough privileges to access public interest data.
    Ok Not OK
- [ ] You currently don’t have permission to access public-funded knowledge.
    OK Request Permission

**Comment by kleidieski** [comment]
Hey @rskikuli do you suggest we just keep it to 12 posters, or are you preparing suggestions for the rest of the messages?

**Comment by rskikuli** [comment]
I'm trying ti edit or not approve the non ticked ones. Please proceed for the moment with the ones that have the checkbox and Ill update this issue once there is a decission for the other ones.  Thanks for the patience :)

**Comment by rskikuli** [comment]
Please keep this on hold @kleidieski until we find someone that will take ownership of the production. Ping @sidorelauku @nafieshehu @silvaarapi and team.

**Comment by sidorelauku** [comment]
I'm closing this.
